image: node:alpine

stages:
    - lint
    - build

eslint:
    stage: lint
    script:
        - npm i
        - npm test

pages:
    stage: build
    script:
        - find . -maxdepth 1 -name '*.html' -exec patch {} demopatch.diff \;
        - ls *.rej 2>/dev/null
        - rm -r getinfo.py package*.json README.md requirements.txt screenshot-*.png demopatch.diff *.orig
        - cp -r * .public
        - mv .public public
    artifacts:
        paths:
            - public
    only:
        - pages
