var lang = "TChinese";
var locale = {
	"English":                         "EN",
	"TChinese":                        "繁",
	"SChinese":                        "简"
};
var localise = {
	"zoomInEnglish":                   "Zoom in",
	"zoomInTChinese":                  "放大",
	"zoomInSChinese":                  "放大",
	"zoomOutEnglish":                  "Zoom out",
	"zoomOutTChinese":                 "縮小",
	"zoomOutSChinese":                 "缩小",
	"unresolvedListEnglish":           "Unresolved list",
	"unresolvedListTChinese":          "未定位單位列表",
	"unresolvedListSChinese":          "未定位单位列表",
	"unresolvedDescEnglish":           "Following is a list of service units with unresolved address, please use Ctrl+F to search.",
	"unresolvedDescTChinese":          "以下爲所有未能定位的服務單位列表，請使用Ctrl+F搜尋。",
	"unresolvedDescSChinese":          "以下為所有未能定位的服务单位列表，请使用Ctrl+F搜寻。",
	"emptyPlaceholderEnglish":         "All service units are resolved, Click back button on top right to return to map.",
	"emptyPlaceholderTChinese":        "所有服務單位已經成功定位，請按右上方返回按鈕以回到地圖。",
	"emptyPlaceholderSChinese":        "所有服务单位已经成功定位，请按右上方返回按纽以回到地图。",
	"backEnglish":                     "Back",
	"backTChinese":                    "返回",
	"backSChinese":                    "返回",
	"infoEnglish":                     "INFORMATION",
	"infoTChinese":                    "院舍資訊",
	"infoSChinese":                    "院舍资讯",
	"nameEnglish":                     "Name: ",
	"nameTChinese":                    "名稱：",
	"nameSChinese":                    "名称：",
	"districtEnglish":                 "District: ",
	"districtTChinese":                "地區：",
	"districtSChinese":                "地区：",
	"addressEnglish":                  "Address: ",
	"addressTChinese":                 "地址：",
	"addressSChinese":                 "地址：",
	"telephoneNumberEnglish":          "Telephone Number: ",
	"telephoneNumberTChinese":         "電話號碼：",
	"telephoneNumberSChinese":         "电话号码：",
	"addTelephoneNumberEnglish":       "Additional Telephone Number: ",
	"addTelephoneNumberTChinese":      "附加電話號碼：",
	"addTelephoneNumberSChinese":      "附加电话号码：",
	"faxNumberEnglish":                "Fax Number: ",
	"faxNumberTChinese":               "傳真號碼：",
	"faxNumberSChinese":               "传真号码：",
	"accreditationEnglish":            "Joined Accreditation Schemes: ",
	"accreditationTChinese":           "參加認證計劃：",
	"accreditationSChinese":           "参加认证计划：",
	"convictionRecordEnglish":         "Conviction Records: ",
	"convictionRecordTChinese":        "有定罪記錄：",
	"convictionRecordSChinese":        "有定罪记录：",
	"typeEnglish":                     "Types: ",
	"typeTChinese":                    "院舍類別：",
	"typeSChinese":                    "院舍类別：",
	"religiousEnglish":                "Religious Background: ",
	"religiousTChinese":               "宗教背景：",
	"religiousSChinese":               "宗教背景：",
	"mealProvisionEnglish":            "Meal Provision: ",
	"mealProvisionTChinese":           "膳食：",
	"mealProvisionSChinese":           "膳食：",
	"typeResentialCareHomesEnglish":   "Type of RCHD: ",
	"typeResentialCareHomesTChinese":  "院舍類別：",
	"typeResentialCareHomesSChinese":  "院舍类别：",
	"addressOverrideEnglish":          "Address Approximation: ",
	"addressOverrideTChinese":         "近似地址：",
	"addressOverrideSChinese":         "近似地址："
};
