var locale = {
	"English":                   "EN",
	"TChinese":                  "繁",
	"SChinese":                  "简"
};
var localise = {
	"unresolvedListEnglish":     "Unresolved list",
	"unresolvedListTChinese":    "未定位單位列表",
	"unresolvedListSChinese":    "未定位单位列表",
	"unresolvedDescEnglish":     "Following is a list of service units with unresolved address, please use Ctrl+F to search.",
	"unresolvedDescTChinese":    "以下爲所有未能定位的服務單位列表，請使用Ctrl+F搜尋。",
	"unresolvedDescSChinese":    "以下為所有未能定位的服务单位列表，请使用Ctrl+F搜寻。",
	"infoEnglish":               "INFORMATION",
	"infoTChinese":              "院舍資訊",
	"infoSChinese":              "院舍资讯",
	"nameEnglish":               "Name: ",
	"nameTChinese":              "名稱：",
	"nameSChinese":              "名称：",
	"districtEnglish":           "District: ",
	"districtTChinese":          "地區：",
	"districtSChinese":          "地区：",
	"addressEnglish":            "Address: ",
	"addressTChinese":           "地址：",
	"addressSChinese":           "地址：",
	"telephoneNumber":           "➰️: ",
	"addTelephoneNumber":        "➰️: ",
	"faxNumber":                 "📠: ",
	"accreditationEnglish":      "Joined Accreditation Schemes: ",
	"accreditationTChinese":     "參加認證計劃：",
	"accreditationSChinese":     "参加认证计划：",
	"convictionRecordEnglish":   "Conviction Records: ",
	"convictionRecordTChinese":  "有定罪記錄：",
	"convictionRecordSChinese":  "有定罪记录：",
	"typeEnglish":               "Types: ",
	"typeTChinese":              "院舍類別：",
	"typeSChinese":              "院舍类別：",
	"religiousEnglish":          "Religious Background: ",
	"religiousTChinese":         "宗教背景：",
	"religiousSChinese":         "宗教背景：",
	"mealProvisionEnglish":      "Meal Provision: ",
	"mealProvisionTChinese":     "膳食：",
	"mealProvisionSChinese":     "膳食：",
};
